/*
 * Copyright (c) 2025, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package opensavvy.ktmongo.dsl

import opensavvy.ktmongo.bson.BsonFactory
import opensavvy.ktmongo.bson.PropertyNameStrategy
import opensavvy.ktmongo.bson.types.ObjectIdGenerator
import kotlin.concurrent.atomics.ExperimentalAtomicApi
import kotlin.time.ExperimentalTime

/**
 * BSON configuration for the objects generated by the DSL.
 *
 * This object is passed through the entire DSL to allow accessing the configuration from anywhere during request generation.
 */
interface BsonContext : BsonFactory, ObjectIdGenerator, PropertyNameStrategy

private class BsonContextImpl(
	bsonFactory: BsonFactory,
	objectIdGenerator: ObjectIdGenerator,
	nameStrategy: PropertyNameStrategy,
) : BsonContext,
	BsonFactory by bsonFactory,
	ObjectIdGenerator by objectIdGenerator,
	PropertyNameStrategy by nameStrategy

/**
 * BSON configuration for the objects generated by the DSL.
 */
@ExperimentalTime
@ExperimentalAtomicApi
fun BsonContext(
	bsonFactory: BsonFactory,
	objectIdGenerator: ObjectIdGenerator = ObjectIdGenerator.Default(),
	nameStrategy: PropertyNameStrategy = PropertyNameStrategy.Default,
): BsonContext = BsonContextImpl(bsonFactory, objectIdGenerator, nameStrategy)
