/*
 * Copyright (c) 2025-2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated from dsl-template/src/commonMain/kotlin/aggregation/operators/ArithmeticValueOperators.kt
// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.

package opensavvy.ktmongo.dsl.aggregation.operators

import opensavvy.ktmongo.bson.BsonValueWriter
import opensavvy.ktmongo.dsl.BsonContext
import opensavvy.ktmongo.dsl.KtMongoDsl
import opensavvy.ktmongo.dsl.LowLevelApi
import opensavvy.ktmongo.dsl.aggregation.AbstractValue
import opensavvy.ktmongo.dsl.aggregation.AggregationOperators
import opensavvy.ktmongo.dsl.aggregation.Value

/**
 * Operators to arithmetically combine two or more values.
 *
 * To learn more about aggregation operators, see [AggregationOperators].
 */
interface ArithmeticValueOperators : ValueOperators {

	// region $abs

	/**
	 * The absolute value of a number.
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val name: String,
	 *     val startTemp: Int,
	 *     val endTemp: Int,
	 *     val diffTemp: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline(filter = { Sensor::diffTemp.isNull() }) {
	 *     set {
	 *         Sensor::diffTemp set abs(Sensor::startTemp - Sensor::endTemp)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/abs/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> abs(value: Value<Context, Result>): Value<Context, Result> =
		UnarySameTypeValueOperator(context, "abs", value)

	/**
	 * The absolute value of a number.
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val name: String,
	 *     val startTemp: Int,
	 *     val endTemp: Int,
	 *     val diffTemp: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline(filter = { Sensor::diffTemp.isNull() }) {
	 *     set {
	 *         Sensor::diffTemp set abs(Sensor::startTemp - Sensor::endTemp)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/abs/)
	 */
	@kotlin.jvm.JvmName("absByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> abs(value: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		abs(of(value))

	/**
	 * The absolute value of a number.
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val name: String,
	 *     val startTemp: Int,
	 *     val endTemp: Int,
	 *     val diffTemp: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline(filter = { Sensor::diffTemp.isNull() }) {
	 *     set {
	 *         Sensor::diffTemp set abs(Sensor::startTemp - Sensor::endTemp)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/abs/)
	 */
	@kotlin.jvm.JvmName("absByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> abs(value: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		abs(of(value))

	/**
	 * The absolute value of a number.
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val name: String,
	 *     val startTemp: Int,
	 *     val endTemp: Int,
	 *     val diffTemp: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline(filter = { Sensor::diffTemp.isNull() }) {
	 *     set {
	 *         Sensor::diffTemp set abs(Sensor::startTemp - Sensor::endTemp)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/abs/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result : Number?> abs(value: Result): Value<Context, Result> =
		abs(of(value))

	// endregion
	// region $add

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.plus(other: Value<Context, Result>): Value<Context, Result> =
		AdditionValueOperator(context, listOf(this, other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.plus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		this.plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.plus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		this.plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Value<Context, Result>.plus(other: Result): Value<Context, Result> =
		this.plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusFieldReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.plus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).plus(other)

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusFieldReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.plus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusFieldReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.plus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusFieldReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.plus(other: Result): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusPropertyReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.plus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).plus(other)

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusPropertyReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.plus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusPropertyReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.plus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.jvm.JvmName("plusPropertyReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> kotlin.reflect.KProperty1<Context, Result>.plus(other: Result): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("plusResultReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.plus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).plus(other)

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("plusResultReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.plus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("plusResultReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.plus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).plus(of(other))

	/**
	 * Sums two aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val price: Int,
	 *     val dailyPriceIncrease: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Product::price set (Product::price + Product::dailyPriceIncrease)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/add/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("plusResultReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.plus(other: Result): Value<Context, Result> =
		of(this).plus(of(other))

	@OptIn(LowLevelApi::class)
	private class AdditionValueOperator<Context : Any, T>(
		context: BsonContext,
		private val operands: List<Value<Context, T>>,
	) : AbstractValue<Context, T>(context) {

		override fun simplify(): AbstractValue<Context, T> {
			val flattenedOperands = ArrayList<Value<Context, T>>()

			for (operand in operands) {
				if (operand is AdditionValueOperator) {
					flattenedOperands += operand.operands
				} else {
					flattenedOperands += operand
				}
			}

			return if (flattenedOperands != operands) {
				AdditionValueOperator(context, flattenedOperands)
			} else {
				this
			}
		}

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				writeArray("\$add") {
					for (operand in operands) {
						operand.writeTo(this)
					}
				}
			}
		}
	}

	// endregion
	// region $ceil

	/**
	 * The smallest integer greater than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val maxBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::maxBound set ceil(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ceil/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> ceil(value: Value<Context, Result>): Value<Context, Result> =
		UnarySameTypeValueOperator(context, "ceil", value)

	/**
	 * The smallest integer greater than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val maxBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::maxBound set ceil(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ceil/)
	 */
	@kotlin.jvm.JvmName("ceilByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> ceil(value: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		ceil(of(value))

	/**
	 * The smallest integer greater than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val maxBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::maxBound set ceil(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ceil/)
	 */
	@kotlin.jvm.JvmName("ceilByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> ceil(value: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		ceil(of(value))

	/**
	 * The smallest integer greater than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val maxBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::maxBound set ceil(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ceil/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result : Number?> ceil(value: Result): Value<Context, Result> =
		ceil(of(value))

	// endregion
	// region $multiply

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.times(other: Value<Context, Result>): Value<Context, Result> =
		MultiplicationValueOperator(context, listOf(this, other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.times(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		this.times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.times(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		this.times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Value<Context, Result>.times(other: Result): Value<Context, Result> =
		this.times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesFieldReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.times(other: Value<Context, Result>): Value<Context, Result> =
		of(this).times(other)

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesFieldReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.times(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesFieldReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.times(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesFieldReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.times(other: Result): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesPropertyReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.times(other: Value<Context, Result>): Value<Context, Result> =
		of(this).times(other)

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesPropertyReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.times(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesPropertyReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.times(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.jvm.JvmName("timesPropertyReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> kotlin.reflect.KProperty1<Context, Result>.times(other: Result): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("timesResultReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.times(other: Value<Context, Result>): Value<Context, Result> =
		of(this).times(other)

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("timesResultReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.times(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("timesResultReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.times(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).times(of(other))

	/**
	 * Multiplies two or more aggregation values.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Double,
	 *     val quantity: Int,
	 *     val total: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price * Sale::quantity)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/multiply/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("timesResultReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.times(other: Result): Value<Context, Result> =
		of(this).times(of(other))

	@OptIn(LowLevelApi::class)
	private class MultiplicationValueOperator<Context : Any, T>(
		context: BsonContext,
		private val operands: List<Value<Context, T>>,
	) : AbstractValue<Context, T>(context) {

		override fun simplify(): AbstractValue<Context, T> {
			val flattenedOperands = ArrayList<Value<Context, T>>()

			for (operand in operands) {
				if (operand is MultiplicationValueOperator) {
					flattenedOperands += operand.operands
				} else {
					flattenedOperands += operand
				}
			}

			return if (flattenedOperands != operands) {
				MultiplicationValueOperator(context, flattenedOperands)
			} else {
				this
			}
		}

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				writeArray("\$multiply") {
					for (operand in operands) {
						operand.writeTo(this)
					}
				}
			}
		}
	}

	// endregion
	// region $divide

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.div(other: Value<Context, Result>): Value<Context, Result> =
		DivisionValueOperator(context, this, other)

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.jvm.JvmName("divByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.div(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		this.div(of(other))

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Value<Context, Result>.div(other: Result): Value<Context, Result> =
		this.div(of(other))

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.jvm.JvmName("divFieldReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.div(other: Value<Context, Result>): Value<Context, Result> =
		of(this).div(other)

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.jvm.JvmName("divFieldReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.div(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).div(of(other))

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.jvm.JvmName("divFieldReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.div(other: Result): Value<Context, Result> =
		of(this).div(of(other))

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("divResultReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.div(other: Value<Context, Result>): Value<Context, Result> =
		of(this).div(other)

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("divResultReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.div(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).div(of(other))

	/**
	 * Divides one aggregation value by another.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class ConferencePlanning(
	 *     val hours: Int,
	 *     val workdays: Double,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         ConferencePlanning::workdays set (of(ConferencePlanning::hours) / of(8))
	 *     }
	 * }
	 * ```
	 *
	 * Note: due to an overload resolution ambiguity with [ValueOperators.div], the [of][ValueOperators.of] operator is
	 * required for at least one of the arguments.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("divResultReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.div(other: Result): Value<Context, Result> =
		of(this).div(of(other))

	@OptIn(LowLevelApi::class)
	private class DivisionValueOperator<Context : Any, T>(
		context: BsonContext,
		private val dividend: Value<Context, T>,
		private val divisor: Value<Context, T>,
	) : AbstractValue<Context, T>(context) {

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				writeArray("\$divide") {
					dividend.writeTo(this)
					divisor.writeTo(this)
				}
			}
		}
	}

	// endregion
	// region $subtract

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.minus(other: Value<Context, Result>): Value<Context, Result> =
		SubtractionValueOperator(context, this, other)

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.minus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		this.minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> Value<Context, Result>.minus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		this.minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Value<Context, Result>.minus(other: Result): Value<Context, Result> =
		this.minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusFieldReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.minus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).minus(other)

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusFieldReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.minus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusFieldReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.minus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusFieldReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.minus(other: Result): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusPropertyReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.minus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).minus(other)

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusPropertyReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.minus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusPropertyReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	operator fun <Context : Any, @kotlin.internal.OnlyInputTypes Result> kotlin.reflect.KProperty1<Context, Result>.minus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.jvm.JvmName("minusPropertyReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> kotlin.reflect.KProperty1<Context, Result>.minus(other: Result): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("minusResultReceiverByValue")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.minus(other: Value<Context, Result>): Value<Context, Result> =
		of(this).minus(other)

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("minusResultReceiverByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.minus(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("minusResultReceiverByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.minus(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		of(this).minus(of(other))

	/**
	 * Subtracts one aggregation value from another.
	 *
	 * The second argument is subtracted from the first argument.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sale(
	 *     val price: Int,
	 *     val fee: Int,
	 *     val discount: Int,
	 *     val total: Int,
	 * )
	 *
	 * collection.updateManyWithPipeline {
	 *     set {
	 *         Sale::total set (Sale::price + Sale::fee - Sale::discount)
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("minusResultReceiverByResult")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	operator final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result> Result.minus(other: Result): Value<Context, Result> =
		of(this).minus(of(other))

	@OptIn(LowLevelApi::class)
	private class SubtractionValueOperator<Context : Any, T>(
		context: BsonContext,
		private val minuend: Value<Context, T>,
		private val subtrahend: Value<Context, T>,
	) : AbstractValue<Context, T>(context) {

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				writeArray("\$subtract") {
					minuend.writeTo(this)
					subtrahend.writeTo(this)
				}
			}
		}
	}

	// endregion
	// region $floor

	/**
	 * The largest integer less than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val minBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::minBound set floor(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/floor/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> floor(value: Value<Context, Result>): Value<Context, Result> =
		UnarySameTypeValueOperator(context, "floor", value)

	/**
	 * The largest integer less than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val minBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::minBound set floor(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/floor/)
	 */
	@kotlin.jvm.JvmName("floorByField")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> floor(value: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Result> =
		floor(of(value))

	/**
	 * The largest integer less than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val minBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::minBound set floor(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/floor/)
	 */
	@kotlin.jvm.JvmName("floorByProperty")
	@OptIn(LowLevelApi::class)
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <Context : Any, @kotlin.internal.OnlyInputTypes Result : Number?> floor(value: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Result> =
		floor(of(value))

	/**
	 * The largest integer less than or equal to the specified [value].
	 *
	 * If the value is `null` or `NaN`, it is returned unchanged.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Sensor(
	 *     val value: Double,
	 *     val minBound: Double,
	 * )
	 *
	 * collection.aggregate()
	 *     .set {
	 *         Sensor::minBound set floor(Sensor::value)
	 *     }.toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/floor/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <Context : Any, @kotlin.internal.OnlyInputTypes reified Result : Number?> floor(value: Result): Value<Context, Result> =
		floor(of(value))

	// endregion

	@LowLevelApi
	private class UnarySameTypeValueOperator<Context : Any, T>(
		context: BsonContext,
		private val operator: String,
		private val value: Value<Context, T>,
	) : AbstractValue<Context, T>(context) {

		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				write("$$operator") {
					value.writeTo(this)
				}
			}
		}
	}
}
