/*
 * Copyright (c) 2024-2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated from dsl-template/src/commonMain/kotlin/aggregation/operators/ComparisonValueOperators.kt
// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.

package opensavvy.ktmongo.dsl.aggregation.operators

import opensavvy.ktmongo.bson.BsonValueWriter
import opensavvy.ktmongo.dsl.BsonContext
import opensavvy.ktmongo.dsl.KtMongoDsl
import opensavvy.ktmongo.dsl.LowLevelApi
import opensavvy.ktmongo.dsl.aggregation.AbstractValue
import opensavvy.ktmongo.dsl.aggregation.AggregationOperators
import opensavvy.ktmongo.dsl.aggregation.Value
import opensavvy.ktmongo.dsl.query.FilterQuery

/**
 * Operators to compare two values.
 *
 * To learn more about aggregation operators, view [AggregationOperators].
 */
interface ComparisonValueOperators : ValueOperators {

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.eq(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "eq")

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.eq(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.eq(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.eq(other: Result): Value<Context, Boolean> =
		this.eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.eq(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).eq(other)

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.eq(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.eq(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.eq(other: Result): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqPropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.eq(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).eq(other)

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqPropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.eq(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqPropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.eq(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("eqPropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.eq(other: Result): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("eqResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.eq(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).eq(other)

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("eqResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.eq(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("eqResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.eq(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val releasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate eq Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see ne Negation of this operator.
	 * @see FilterQuery.eq Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("eqResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.eq(other: Result): Value<Context, Boolean> =
		of(this).eq(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.ne(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "ne")

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.ne(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.ne(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.ne(other: Result): Value<Context, Boolean> =
		this.ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.ne(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).ne(other)

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.ne(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.ne(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("neFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.ne(other: Result): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("nePropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.ne(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).ne(other)

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("nePropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.ne(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("nePropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.ne(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.jvm.JvmName("nePropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.ne(other: Result): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("neResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.ne(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).ne(other)

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("neResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.ne(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("neResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.ne(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).ne(of(other))

	/**
	 * Compares two aggregation values and returns `true` if they are not equivalent.
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class Product(
	 *     val name: String,
	 *     val creationDate: Instant,
	 *     val releaseDate: Instant,
	 * )
	 *
	 * val notReleasedOnCreation = collection.aggregate()
	 *     .match {
	 *         expr {
	 *             Product::creationDate ne Product::releaseDate
	 *         }
	 *     }
	 *     .toList()
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ne/)
	 * - [Comparison algorithm](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#std-label-bson-types-comparison-order)
	 *
	 * @see eq Negation of this operator.
	 * @see FilterQuery.ne Equivalent operator in regular queries.
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("neResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.ne(other: Result): Value<Context, Boolean> =
		of(this).ne(of(other))

	// TODO: document the other operators once 'project' is implemented, since the official examples use 'project' to demonstrate them

	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gt(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "gt")

	@kotlin.jvm.JvmName("gtByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.gt(of(other))

	@kotlin.jvm.JvmName("gtByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.gt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.gt(other: Result): Value<Context, Boolean> =
		this.gt(of(other))

	@kotlin.jvm.JvmName("gtFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gt(other)

	@kotlin.jvm.JvmName("gtFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.jvm.JvmName("gtFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.jvm.JvmName("gtFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gt(other: Result): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.jvm.JvmName("gtPropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gt(other)

	@kotlin.jvm.JvmName("gtPropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.jvm.JvmName("gtPropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.jvm.JvmName("gtPropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.gt(other: Result): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gtResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gt(other)

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gtResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gtResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gtResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gt(other: Result): Value<Context, Boolean> =
		of(this).gt(of(other))

	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gte(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "gte")

	@kotlin.jvm.JvmName("gteByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.gte(of(other))

	@kotlin.jvm.JvmName("gteByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.gte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.gte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.gte(other: Result): Value<Context, Boolean> =
		this.gte(of(other))

	@kotlin.jvm.JvmName("gteFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gte(other)

	@kotlin.jvm.JvmName("gteFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.jvm.JvmName("gteFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.jvm.JvmName("gteFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.gte(other: Result): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.jvm.JvmName("gtePropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gte(other)

	@kotlin.jvm.JvmName("gtePropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.jvm.JvmName("gtePropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.gte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.jvm.JvmName("gtePropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.gte(other: Result): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gteResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).gte(other)

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gteResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gteResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).gte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("gteResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.gte(other: Result): Value<Context, Boolean> =
		of(this).gte(of(other))

	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lt(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "lt")

	@kotlin.jvm.JvmName("ltByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.lt(of(other))

	@kotlin.jvm.JvmName("ltByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.lt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.lt(other: Result): Value<Context, Boolean> =
		this.lt(of(other))

	@kotlin.jvm.JvmName("ltFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lt(other)

	@kotlin.jvm.JvmName("ltFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.jvm.JvmName("ltFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.jvm.JvmName("ltFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lt(other: Result): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.jvm.JvmName("ltPropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lt(other)

	@kotlin.jvm.JvmName("ltPropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.jvm.JvmName("ltPropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.jvm.JvmName("ltPropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.lt(other: Result): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("ltResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lt(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lt(other)

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("ltResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lt(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("ltResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lt(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lt(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("ltResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lt(other: Result): Value<Context, Boolean> =
		of(this).lt(of(other))

	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lte(other: Value<Context, Result>): Value<Context, Boolean> =
		ComparisonValueOperator(context, this, other, "lte")

	@kotlin.jvm.JvmName("lteByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		this.lte(of(other))

	@kotlin.jvm.JvmName("lteByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> Value<Context, Result>.lte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		this.lte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Value<Context, Result>.lte(other: Result): Value<Context, Boolean> =
		this.lte(of(other))

	@kotlin.jvm.JvmName("lteFieldReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lte(other)

	@kotlin.jvm.JvmName("lteFieldReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.jvm.JvmName("lteFieldReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.jvm.JvmName("lteFieldReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> opensavvy.ktmongo.dsl.path.Field<Context, Result>.lte(other: Result): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.jvm.JvmName("ltePropertyReceiverByValue")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lte(other)

	@kotlin.jvm.JvmName("ltePropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.jvm.JvmName("ltePropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix fun <Context : Any, Result> kotlin.reflect.KProperty1<Context, Result>.lte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.jvm.JvmName("ltePropertyReceiverByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> kotlin.reflect.KProperty1<Context, Result>.lte(other: Result): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("lteResultReceiverByValue")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lte(other: Value<Context, Result>): Value<Context, Boolean> =
		of(this).lte(other)

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("lteResultReceiverByField")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lte(other: opensavvy.ktmongo.dsl.path.Field<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("lteResultReceiverByProperty")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lte(other: kotlin.reflect.KProperty1<Context, Result>): Value<Context, Boolean> =
		of(this).lte(of(other))

	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("lteResultReceiverByResult")
	@Suppress("INVISIBLE_REFERENCE", "INAPPLICABLE_JVM_NAME", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@OptIn(LowLevelApi::class)
	@KtMongoDsl
	infix final inline fun <Context : Any, reified Result> Result.lte(other: Result): Value<Context, Boolean> =
		of(this).lte(of(other))

	@OptIn(LowLevelApi::class)
	private class ComparisonValueOperator<Context : Any, T>(
		context: BsonContext,
		private val operandA: Value<Context, T>,
		private val operandB: Value<Context, T>,
		private val operator: String,
	) : AbstractValue<Context, Boolean>(context) {

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				writeArray("$$operator") {
					operandA.writeTo(this)
					operandB.writeTo(this)
				}
			}
		}
	}
}
