/*
 * Copyright (c) 2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated from dsl-template/src/commonMain/kotlin/aggregation/operators/DateTimeValueOperators.kt
// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.

package opensavvy.ktmongo.dsl.aggregation.operators

import opensavvy.ktmongo.bson.BsonValueWriter
import opensavvy.ktmongo.bson.types.ObjectId
import opensavvy.ktmongo.bson.types.Timestamp
import opensavvy.ktmongo.dsl.BsonContext
import opensavvy.ktmongo.dsl.KtMongoDsl
import opensavvy.ktmongo.dsl.LowLevelApi
import opensavvy.ktmongo.dsl.aggregation.AbstractValue
import opensavvy.ktmongo.dsl.aggregation.AggregationOperators
import opensavvy.ktmongo.dsl.aggregation.Value
import kotlin.jvm.JvmName
import kotlin.time.Instant

/**
 * Operators to manage date and time values.
 *
 * To learn more about aggregation operators, view [AggregationOperators].
 */
@KtMongoDsl
interface DateTimeValueOperators : ValueOperators {

	// region $year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.year: Value<R, Int>
		get() = UnaryOperator(context, "year", this)

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.year: Value<Any, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfObjectId")
	final val <R : Any> Value<R, ObjectId>.year: Value<R, Int>
		get() = UnaryOperator(context, "year", this)

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfObjectId")
	final val ObjectId.year: Value<Any, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.year: Value<R, Int>
		get() = UnaryOperator(context, "year", this)

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.year: Value<R, Int>
		get() = of(this).year

	/**
	 * Returns the year portion of a date.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthyear: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthyear set User::birthdate.year
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/year/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("yearOfTimestamp")
	final val Timestamp.year: Value<Any, Int>
		get() = of(this).year

	// endregion
	// region $week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.week: Value<R, Int>
		get() = UnaryOperator(context, "week", this)

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.week: Value<Any, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfObjectId")
	final val <R : Any> Value<R, ObjectId>.week: Value<R, Int>
		get() = UnaryOperator(context, "week", this)

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfObjectId")
	final val ObjectId.week: Value<Any, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.week: Value<R, Int>
		get() = UnaryOperator(context, "week", this)

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.week: Value<R, Int>
		get() = of(this).week

	/**
	 * Returns the week of the year for a date, ranging from `0` to `53`.
	 *
	 * Weeks begin on Sundays, and week `1` begins with the first Sunday of the year. Days
	 * preceding the first Sunday of the year are in week `0`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweek: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweek set User::birthdate.week
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/week/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekOfTimestamp")
	final val Timestamp.week: Value<Any, Int>
		get() = of(this).week

	// endregion
	// region $second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.second: Value<R, Int>
		get() = UnaryOperator(context, "second", this)

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.second: Value<Any, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfObjectId")
	final val <R : Any> Value<R, ObjectId>.second: Value<R, Int>
		get() = UnaryOperator(context, "second", this)

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfObjectId")
	final val ObjectId.second: Value<Any, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.second: Value<R, Int>
		get() = UnaryOperator(context, "second", this)

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.second: Value<R, Int>
		get() = of(this).second

	/**
	 * Returns the second portion of a date as a number between `0` and `60` (leap seconds).
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthsecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthsecond set User::birthdate.second
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/second/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("secondOfTimestamp")
	final val Timestamp.second: Value<Any, Int>
		get() = of(this).second

	// endregion
	// region $month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.month: Value<R, Int>
		get() = UnaryOperator(context, "month", this)

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.month: Value<Any, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfObjectId")
	final val <R : Any> Value<R, ObjectId>.month: Value<R, Int>
		get() = UnaryOperator(context, "month", this)

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfObjectId")
	final val ObjectId.month: Value<Any, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.month: Value<R, Int>
		get() = UnaryOperator(context, "month", this)

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.month: Value<R, Int>
		get() = of(this).month

	/**
	 * Returns the month of a date as a number between `1` and `12`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmonth: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmonth set User::birthdate.month
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/month/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("monthOfTimestamp")
	final val Timestamp.month: Value<Any, Int>
		get() = of(this).month

	// endregion
	// region $minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.minute: Value<R, Int>
		get() = UnaryOperator(context, "minute", this)

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.minute: Value<Any, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfObjectId")
	final val <R : Any> Value<R, ObjectId>.minute: Value<R, Int>
		get() = UnaryOperator(context, "minute", this)

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfObjectId")
	final val ObjectId.minute: Value<Any, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.minute: Value<R, Int>
		get() = UnaryOperator(context, "minute", this)

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.minute: Value<R, Int>
		get() = of(this).minute

	/**
	 * Returns the minute portion of a date as a number between `0` and `59`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthminute: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthminute set User::birthdate.minute
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/minute/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("minuteOfTimestamp")
	final val Timestamp.minute: Value<Any, Int>
		get() = of(this).minute

	// endregion
	// region $millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.millisecond: Value<R, Int>
		get() = UnaryOperator(context, "millisecond", this)

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.millisecond: Value<Any, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfObjectId")
	final val <R : Any> Value<R, ObjectId>.millisecond: Value<R, Int>
		get() = UnaryOperator(context, "millisecond", this)

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfObjectId")
	final val ObjectId.millisecond: Value<Any, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.millisecond: Value<R, Int>
		get() = UnaryOperator(context, "millisecond", this)

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.millisecond: Value<R, Int>
		get() = of(this).millisecond

	/**
	 * Returns the millisecond portion of a date as a number between `0` and `999`.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthmillisecond: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthmillisecond set User::birthdate.millisecond
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/millisecond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("millisecondOfTimestamp")
	final val Timestamp.millisecond: Value<Any, Int>
		get() = of(this).millisecond

	// endregion
	// region $isoWeek

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> Value<R, Instant>.weekIso: Value<R, Int>
		get() = UnaryOperator(context, "isoWeek", this)

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Instant>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	val <R : Any> kotlin.reflect.KProperty1<R, Instant>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE")
	@OptIn(LowLevelApi::class)
	val Instant.weekIso: Value<Any, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfObjectId")
	final val <R : Any> Value<R, ObjectId>.weekIso: Value<R, Int>
		get() = UnaryOperator(context, "isoWeek", this)

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfObjectId")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, ObjectId>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfObjectId")
	final val <R : Any> kotlin.reflect.KProperty1<R, ObjectId>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfObjectId")
	final val ObjectId.weekIso: Value<Any, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfTimestamp")
	final val <R : Any> Value<R, Timestamp>.weekIso: Value<R, Int>
		get() = UnaryOperator(context, "isoWeek", this)

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfTimestamp")
	final val <R : Any> opensavvy.ktmongo.dsl.path.Field<R, Timestamp>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@OptIn(LowLevelApi::class)
	@Suppress("WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfTimestamp")
	final val <R : Any> kotlin.reflect.KProperty1<R, Timestamp>.weekIso: Value<R, Int>
		get() = of(this).weekIso

	/**
	 * Returns the week number in ISO 8601 format, ranging from `1` to `53`.
	 *
	 * Week numbers start at `1` with the week (Monday through Sunday) that contains the year's
	 * first Thursday.
	 *
	 * The accepted date types are [Instant], [ObjectId] and [Timestamp].
	 *
	 * ### Example
	 *
	 * ```kotlin
	 * class User(
	 *     val name: String,
	 *     val birthdate: Instant,
	 *     val birthweekIso: Int? = null,
	 * )
	 *
	 * users.updateManyWithPipeline {
	 *     set {
	 *         User::birthweekIso set User::birthdate.weekIso
	 *     }
	 * }
	 * ```
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoWeek/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@OptIn(LowLevelApi::class)
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@get:JvmName("weekIsoOfTimestamp")
	final val Timestamp.weekIso: Value<Any, Int>
		get() = of(this).weekIso

	// endregion

	@LowLevelApi
	private class UnaryOperator<Root : Any, Input, Output>(
		context: BsonContext,
		private val operator: String,
		private val input: Value<Root, Input>,
	) : AbstractValue<Root, Output>(context) {

		@LowLevelApi
		override fun write(writer: BsonValueWriter) = with(writer) {
			writeDocument {
				write("$$operator") {
					input.writeTo(this)
				}
			}
		}
	}
}
