/*
 * Copyright (c) 2024-2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated from dsl-template/src/commonMain/kotlin/aggregation/stages/Set.kt
// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.

package opensavvy.ktmongo.dsl.aggregation.stages

import opensavvy.ktmongo.bson.BsonFieldWriter
import opensavvy.ktmongo.dsl.BsonContext
import opensavvy.ktmongo.dsl.DangerousMongoApi
import opensavvy.ktmongo.dsl.KtMongoDsl
import opensavvy.ktmongo.dsl.LowLevelApi
import opensavvy.ktmongo.dsl.aggregation.AggregationOperators
import opensavvy.ktmongo.dsl.aggregation.Pipeline
import opensavvy.ktmongo.dsl.aggregation.Value
import opensavvy.ktmongo.dsl.path.Field
import opensavvy.ktmongo.dsl.path.FieldDsl
import opensavvy.ktmongo.dsl.path.Path
import opensavvy.ktmongo.dsl.tree.AbstractBsonNode
import opensavvy.ktmongo.dsl.tree.AbstractCompoundBsonNode
import opensavvy.ktmongo.dsl.tree.BsonNode
import opensavvy.ktmongo.dsl.tree.CompoundBsonNode

/**
 * Pipeline implementing the `$set` stage.
 */
@KtMongoDsl
interface HasSet<Document : Any> : Pipeline<Document> {

	/**
	 * Adds new fields to documents, or overwrites existing fields.
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/set/)
	 */
	@KtMongoDsl
	@OptIn(DangerousMongoApi::class, LowLevelApi::class)
	fun set(
		block: SetStageOperators<Document>.() -> Unit,
	): Pipeline<Document> =
		withStage(createSetStage(context, block))

}

@OptIn(LowLevelApi::class)
private class SetStage(
	val expression: SetStageOperators<*>,
	context: BsonContext,
) : AbstractBsonNode(context) {
	override fun write(writer: BsonFieldWriter) = with(writer) {
		writeDocument("\$set") {
			expression.writeTo(this)
		}
	}
}

internal fun <Document : Any> createSetStage(context: BsonContext, block: SetStageOperators<Document>.() -> Unit): BsonNode =
	SetStage(SetStageBsonNode<Document>(context).apply(block), context)

/**
 * The operators allowed in a [set] stage.
 */
@KtMongoDsl
interface SetStageOperators<T : Any> : CompoundBsonNode, AggregationOperators, FieldDsl {

	// region $set

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.set(value: Value<T, V>)

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@kotlin.jvm.JvmName("setByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.set(value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@kotlin.jvm.JvmName("setPropertyReceiverByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.set(value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@kotlin.jvm.JvmName("setByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.set(value: kotlin.reflect.KProperty1<T, V>) =
		set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@kotlin.jvm.JvmName("setPropertyReceiverByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.set(value: kotlin.reflect.KProperty1<T, V>) =
		this.field.set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	infix final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.set(value: V) =
		set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	infix final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.set(value: V) =
		this.field.set(of(value))

	/**
	 * Replaces the value of a field with the specified [value].
	 *
	 * ### External resources
	 *
	 * - [Official documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	infix fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.set(value: Value<T, V>) {
		return this.field.set(value)
	}

	// endregion
	// region Conditional $set

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Value<T, Boolean>, value: Value<T, V>) =
		this set cond(condition, value, of(this))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByValueByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Value<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByValueByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Value<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByValueByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Value<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByValueByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Value<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setIf(condition: Value<T, Boolean>, value: V) =
		setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Value<T, Boolean>, value: V) =
		this.field.setIf(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByFieldByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: Value<T, V>) =
		setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByFieldByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: Value<T, V>) =
		this.field.setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByFieldByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByFieldByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByFieldByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByFieldByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setIfByFieldByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: V) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByFieldByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setIf(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: V) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByPropertyByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: Value<T, V>) =
		setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByPropertyByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: Value<T, V>) =
		this.field.setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByPropertyByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByPropertyByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfByPropertyByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByPropertyByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setIfByPropertyByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: V) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByPropertyByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setIf(condition: kotlin.reflect.KProperty1<T, Boolean>, value: V) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Boolean, value: Value<T, V>) =
		setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Boolean, value: Value<T, V>) =
		this.field.setIf(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setIfByResultByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Boolean, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByResultByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Boolean, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setIfByResultByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setIf(condition: Boolean, value: kotlin.reflect.KProperty1<T, V>) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setIfPropertyReceiverByResultByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Boolean, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setIf(condition: Boolean, value: V) =
		setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Boolean, value: V) =
		this.field.setIf(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `true`.
	 *
	 * If [condition] is `false`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setIf(condition: Value<T, Boolean>, value: Value<T, V>) {
		return this.field.setIf(condition, value)
	}

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Value<T, Boolean>, value: Value<T, V>) =
		this set cond(condition, of(this), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByValueByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Value<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByValueByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Value<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByValueByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Value<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByValueByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Value<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setUnless(condition: Value<T, Boolean>, value: V) =
		setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Value<T, Boolean>, value: V) =
		this.field.setUnless(condition, of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByFieldByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: Value<T, V>) =
		setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByFieldByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: Value<T, V>) =
		this.field.setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByFieldByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByFieldByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByFieldByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByFieldByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setUnlessByFieldByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: V) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByFieldByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: opensavvy.ktmongo.dsl.path.Field<T, Boolean>, value: V) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByPropertyByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: Value<T, V>) =
		setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByPropertyByValue")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: Value<T, V>) =
		this.field.setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByPropertyByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByPropertyByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessByPropertyByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByPropertyByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setUnlessByPropertyByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: V) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByPropertyByResult")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: kotlin.reflect.KProperty1<T, Boolean>, value: V) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Boolean, value: Value<T, V>) =
		setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Boolean, value: Value<T, V>) =
		this.field.setUnless(of(condition), value)

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setUnlessByResultByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Boolean, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByResultByField")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Boolean, value: opensavvy.ktmongo.dsl.path.Field<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@kotlin.jvm.JvmName("setUnlessByResultByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> Field<T, V>.setUnless(condition: Boolean, value: kotlin.reflect.KProperty1<T, V>) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.jvm.JvmName("setUnlessPropertyReceiverByResultByProperty")
	@Suppress("INAPPLICABLE_JVM_NAME", "INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Boolean, value: kotlin.reflect.KProperty1<T, V>) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@kotlin.internal.LowPriorityInOverloadResolution
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> Field<T, V>.setUnless(condition: Boolean, value: V) =
		setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE", "WRONG_MODIFIER_CONTAINING_DECLARATION")
	@KtMongoDsl
	final inline fun <@kotlin.internal.OnlyInputTypes reified V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Boolean, value: V) =
		this.field.setUnless(of(condition), of(value))

	/**
	 * Replaces the value of a field with the specified [value], if [condition] is `false`.
	 *
	 * If [condition] is `true`, this operator does nothing.
	 *
	 * ### External resources
	 *
	 * - [`$set`](https://www.mongodb.com/docs/manual/reference/operator/update/set/)
	 * - [`$cond`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/cond/)
	 */
	@Suppress("INVISIBLE_REFERENCE")
	@KtMongoDsl
	fun <@kotlin.internal.OnlyInputTypes V> kotlin.reflect.KProperty1<T, V>.setUnless(condition: Value<T, Boolean>, value: Value<T, V>) {
		return this.field.setUnless(condition, value)
	}

	// endregion
}

private class SetStageBsonNode<T : Any>(
	context: BsonContext,
) : AbstractCompoundBsonNode(context), SetStageOperators<T> {

	@OptIn(DangerousMongoApi::class, LowLevelApi::class)
	override fun <V> Field<T, V>.set(value: Value<T, V>) {
		accept(SetBsonNode(this.path, value, context))
	}

	@LowLevelApi
	private class SetBsonNode(
		val path: Path,
		val value: Value<*, *>,
		context: BsonContext,
	) : AbstractBsonNode(context) {

		override fun write(writer: BsonFieldWriter) = with(writer) {
			write(path.toString()) {
				value.writeTo(this)
			}
		}
	}
}
