/*
 * Copyright (c) 2024-2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated from dsl-template/src/commonMain/kotlin/tree/BsonNode.kt
// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.

package opensavvy.ktmongo.dsl.tree

import opensavvy.ktmongo.bson.BsonDocument
import opensavvy.ktmongo.bson.BsonFieldWriteable
import opensavvy.ktmongo.bson.BsonFieldWriter
import opensavvy.ktmongo.dsl.BsonContext
import opensavvy.ktmongo.dsl.DangerousMongoApi
import opensavvy.ktmongo.dsl.KtMongoDsl
import opensavvy.ktmongo.dsl.LowLevelApi
import opensavvy.ktmongo.dsl.query.FilterQueryPredicate

/**
 * A node in the BSON AST.
 *
 * Each implementation of this interface is a logical BSON node in our own intermediary representation.
 * Each node knows how to [writeTo] itself into a BSON document.
 *
 * To learn more about how the tree is formed, see [Node].
 *
 * ### Security
 *
 * Implementing this interface allows injecting arbitrary BSON into a request. Be very careful not to make injections possible.
 *
 * ### Implementation notes
 *
 * Prefer implementing [AbstractBsonNode] instead of implementing this interface directly.
 *
 * ### Debugging notes
 *
 * Use [toString][Any.toString] to view the JSON representation of this expression.
 */
@KtMongoDsl
interface BsonNode : Node, BsonFieldWriteable {

	/**
	 * The context used to generate this expression.
	 */
	@LowLevelApi
	val context: BsonContext

	@LowLevelApi
	override fun freeze()

	/**
	 * Returns a simplified (but equivalent) expression to the current expression.
	 *
	 * Returns `null` when the current expression was simplified into a no-op (= it does nothing).
	 */
	@LowLevelApi
	fun simplify(): BsonNode?

	/**
	 * Writes the result of [simplifying][simplify] this expression into [writer].
	 */
	@LowLevelApi
	override fun writeTo(writer: BsonFieldWriter)

	/**
	 * Writes the result of [simplifying][simplify] to a new [BsonDocument].
	 */
	@LowLevelApi
	fun toBson(): BsonDocument =
		context.buildDocument { writeTo(this) }

	/**
	 * JSON representation of this expression.
	 */
	override fun toString(): String

	companion object
}

/**
 * Utility implementation for [BsonNode], which handles the [context], [toString] representation and [freezing][freeze].
 *
 * ### Implementing a new operator
 *
 * Instances of this class are BSON operators, like `$eq`, `$xor`, `$setOnInsert` and `$lookup`.
 *
 * **Custom operators bypass the entirety of the safety features provided by this library.
 * Because they are able to write arbitrary BSON, no checks whatsoever are possible.
 * If you are not careful, this may make injection attacks or data leaking possible.**
 *
 * Before writing your own operator, familiarize yourself with the documentation of [BsonNode], [AbstractBsonNode],
 * [CompoundBsonNode] and [AbstractCompoundBsonNode], as well as [BsonFieldWriter].
 *
 * Fundamentally, an operator is anything that is able to [write] itself into a BSON document.
 * Operators should not be mutable, except through their [accept][CompoundBsonNode.accept] method (if they have one).
 *
 * An operator generally looks like the following:
 * ```kotlin
 * @LowLevelApi
 * private class TypePredicateExpressionNode(
 *     val type: BsonType,
 *     context: BsonContext,
 * ) : AbstractBsonNode(context) {
 *
 *     override fun write(writer: BsonFieldWriter) {
 *         writer.writeInt32("\$type", type.code)
 *     }
 * }
 * ```
 * The [BsonContext] is required at construction because it is needed to implement [toString], which the user could call at any time,
 * including while the operator is being constructed (e.g. when using a debugger). It is extremely important that the
 * `toString` representation they see is consistent with the final BSON sent over the wire.
 *
 * Once you have created your operator, use the [accept][CompoundBsonNode.accept] method to register it into a DSL:
 * ```kotlin
 * collection.find {
 *     User::name {
 *         accept(TypePredicateExpressionNode(BsonType.Undefined))
 *     }
 * }
 * ```
 *
 * Since [accept][CompoundBsonNode.accept] is marked [DangerousMongoApi], you will get an error on every usage.
 * To avoid this, create a high-level operator function that hides your operator implementation:
 * ```kotlin
 * @OptIn(DangerousMongoApi::class, LowLevelApi::class) // Accept the warnings since this function has a type-safe API
 * context(dsl: FilterQueryPredicate<T>) // Important! Find the right type depending on the context in which the operator is used
 * fun <T> hasType(type: BsonType) {
 *     dsl.accept(TypePredicateExpressionNode(type))
 * }
 *
 * // Usage
 * collection.find {
 *     User::name {
 *         hasType(BsonType.Undefined)
 *     }
 * }
 * ```
 *
 * Of course, the operator described above is already made available: [FilterQueryPredicate.hasType].
 *
 * **Note that if your operator accepts a variable number of sub-expressions (e.g. `$and`), you must ensure that it works for any
 * number of sub-expressions, including 1 and 0.** See [simplify]. For example, a `$and` with a single sub-expression simplifies
 * itself to that sub-expression; the `$and` operator itself disappears.
 *
 * To create an operator that can accept multiple children operators (for example `$and`), implement [AbstractCompoundBsonNode].
 *
 * Since operators are complex to write, risky to get wrong, and hard to test, we highly recommend to upstream any
 * operator you create so they can benefit from future fixes. Again, **an improperly-written operator may allow data
 * corruption or leaking**.
 *
 * Operators should preferably be immutable. To create mutable operators, prefer using [AbstractCompoundBsonNode].
 * Note that once [frozen] is `true`, operators **must be immutable forever**, or other features of this library will break.
 */
abstract class AbstractBsonNode private constructor(
	@property:LowLevelApi override val context: BsonContext,
	private val node: NodeImpl,
) : Node by node, BsonNode {

	constructor(context: BsonContext) : this(context, NodeImpl())

	/**
	 * Starts at `false`. Becomes `true` after [freeze] is called. Can never become `false` again.
	 *
	 * If this value is `true`, this node should reject any attempt to mutate it.
	 * It is the responsibility of the implementor to satisfy this invariant.
	 *
	 * ### Thread safety
	 *
	 * If `false` is read, no thread safety is guaranteed.
	 *
	 * If `true` is read, then happens-after is guaranteed with the first call to [freeze] on this instance.
	 * Since all mutations are forbidden by contract after a call to [freeze], this instance is considered thread-safe.
	 */
	protected val frozen: Boolean
		get() = node.frozen

	/**
	 * Called when this operator should be written to a [writer].
	 *
	 * Note that this function is only called on instances that have passed through [simplify],
	 * so it is guaranteed that this expression is fully simplified already.
	 */
	@LowLevelApi
	protected abstract fun write(writer: BsonFieldWriter)

	@LowLevelApi
	override fun simplify(): AbstractBsonNode? = this

	@LowLevelApi
	final override fun writeTo(writer: BsonFieldWriter) {
		// 'frozen' is a memory fence
		val _ = frozen

		this.simplify()?.write(writer)
	}

	/**
	 * JSON representation of this expression.
	 *
	 * By default, simplifications are enabled.
	 * Set [simplified] to `false` to disable simplifications.
	 */
	@OptIn(LowLevelApi::class)
	fun toString(simplified: Boolean): String {
		val document = context.buildDocument {
			if (simplified)
				writeTo(this)
			else
				write(this)
		}

		return document.toString()
	}

	final override fun toString(): String =
		toString(simplified = true)

	companion object
}

/**
 * A [BsonNode] that contains all the fields of [a] and also all the fields of [b].
 */
@OptIn(LowLevelApi::class)
internal class MergedBsonNode(
	val a: BsonNode,
	val b: BsonNode,
) : BsonNode {

	init {
		require(a.context == b.context) { "Cannot merge nodes with different contexts: ${a.context} and ${b.context}" }
		a.freeze()
		b.freeze()
	}

	@LowLevelApi
	override val context: BsonContext
		get() = a.context

	@LowLevelApi
	override fun freeze() {
		// Nothing to do, children are frozen on instantiation
	}

	@LowLevelApi
	override fun simplify(): BsonNode? {
		val aSimplified = a.simplify()
		val bSimplified = b.simplify()

		return when {
			aSimplified == null -> bSimplified
			bSimplified == null -> aSimplified
			aSimplified == a && bSimplified == b -> this
			else -> MergedBsonNode(aSimplified, bSimplified)
		}
	}

	@LowLevelApi
	override fun writeTo(writer: BsonFieldWriter) {
		a.writeTo(writer)
		b.writeTo(writer)
	}

	override fun toString(): String =
		context.buildDocument {
			simplify()?.writeTo(this)
		}.toString()

}
