/*
 * Copyright (c) 2026, OpenSavvy and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package opensavvy.ktmongo.build

import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.ChangeType
import org.gradle.work.Incremental
import org.gradle.work.InputChanges
import java.io.File

/**
 * Copies the `dsl-template` sources into this project, adding convenience overloads in the process.
 *
 * To learn more, see [the :dsl-template README](../dsl-template/README.md).
 */
abstract class ApplyTemplateTask : DefaultTask() {

	@get:Incremental
	@get:InputDirectory
	abstract val sourceDir: DirectoryProperty

	@get:OutputDirectory
	abstract val outputDir: DirectoryProperty

	@get:Input
	abstract val projectRootDir: Property<File>

	@TaskAction
	fun generate(changes: InputChanges) {
		val src = sourceDir.get().asFile
		val dest = outputDir.get().asFile

		changes.getFileChanges(sourceDir).forEach { change ->
			val relative = change.file.relativeTo(src)
			val destFile = dest.resolve(relative)

			when (change.changeType) {
				ChangeType.REMOVED -> destFile.delete()
				ChangeType.ADDED, ChangeType.MODIFIED -> {
					destFile.parentFile.mkdirs()
					logger.info("Templating file $destFile")
					destFile.writeText(change.file.readText().applyTemplate(change.file.relativeTo(projectRootDir.get())))
				}
			}
		}
	}

	private fun String.applyTemplate(sourceFile: File): String {
		val stream = CharStreams.fromString(this)
		val lexer = opensavvy.ktmongo.build.kotlin.KotlinLexer(stream)
		val tokens = CommonTokenStream(lexer)
		val parser = opensavvy.ktmongo.build.kotlin.KotlinParser(tokens)
		val tree = parser.kotlinFile()

		val rewriter = org.antlr.v4.runtime.TokenStreamRewriter(tokens)

		val walker = org.antlr.v4.runtime.tree.ParseTreeWalker()
		val listener = object : opensavvy.ktmongo.build.kotlin.KotlinParserBaseListener() {
			override fun exitFunctionDeclaration(ctx: opensavvy.ktmongo.build.kotlin.KotlinParser.FunctionDeclarationContext) {
				// rewriter.insertAfter(ctx.stop, " // seen!")
			}
		}
		walker.walk(listener, tree)

		return buildString {
			val text = rewriter.text
			val endOfCopyright = "limitations under the License.\n */\n"
			val indexEndOfCopyright = text.indexOf(endOfCopyright) + endOfCopyright.length

			appendLine(text.substring(0, indexEndOfCopyright))

			appendLine("// This file is generated from $sourceFile")
			appendLine("// DO NOT EDIT THIS FILE DIRECTLY. To learn more, read dsl-template/README.md.")

			append(text.substring(indexEndOfCopyright))
		}
	}
}
